### ISSUE TITLE
B0

### ISSUE THREAD

**Issue by hellotuitu** [Crystal-jiang/web_tasks#1]
- 访问器不是这样用的,使用了访问器就不需要再定义set和get方法了.
- Array自带的sort方法可以满足你的需求,没有必要重复造轮子.
- 代码风格问题, `if val=="y"`应该写成`if val == 'y'`等等
- 判断是否为空有更ruby的写法, `object.nil?`

代码写的很好,已经像是一个rubyer了.

**Comment by pujiaxun** [comment]
rubist 哈哈哈哈

**Comment by Crystal-jiang** [comment]
来自脸哥的嘲笑。。。

**Comment by Crystal-jiang** [comment]
4个问题都依次修改了，请亲查收hhhh

**Comment by hellotuitu** [comment]
改的挺好的, 先鼓励一下.但...还是有一些微小的问题
- 第23行` t = 0 `是什么意思?忘了删?
- 你似乎是把所有的学生对象转换成了hash再存入yaml中的, 其实yaml是可以直接存student类对象的
- 循环一百次可以用`100.times { |index|  ... }`.
- 代码中出现了很多`if !(...)`这样的形式, 不妨尝试用`unless`, 它就等于`if not`
- 并不需要对每一个属性声明访问器, 可以这样`attr_reader :id,:name,:age,:gender`, 如果你是出于代码美观考虑的话,请忽略这一条.

总的来说, 短时间内能达到这样的程度已经很好了,但是还是有可以改进的地方,我这次说的问题可以不用修改了,以后注意就行.还有很重要的一点就是,*不要局限于我给你提出的issue, 你完全可以做的更好*
